name: Generate GPA Badge

on:
  push:
    paths:
      - 'assets/grades.xlsx'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 매주 월요일 실행
permissions:
  contents: write
  
jobs:
  generate-badge:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.18

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run GPA script
      run: python generate_gpa.py

    - name: Push to arenran02/arenran02
      run: |
        git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/arenran02/arenran02.git out
        cp gpa_badge.svg out/
        cd out
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add gpa_badge.svg
        git commit -m "Update GPA badge" || echo "No changes"
        git push